export const FETCH_ALL_ANIME = 'FETCH_ALL_ANIME';
export const FETCH_ALL_ANIME_STARTED = 'FETCH_ALL_ANIME_STARTED';
export const FETCH_ALL_ANIME_ENDED = 'FETCH_ALL_ANIME_ENDED';
export const FETCH_SINGLE_ANIME_STARTED = 'FETCH_SINGLE_ANIME_STARTED';
export const FETCH_SINGLE_ANIME_ENDED = 'FETCH_SINGLE_ANIME_ENDED';
export const FETCH_SINGLE_ANIME_CHARACTERS = 'FETCH_SINGLE_ANIME_CHARACTERS';
